name: Deploy Dokka Docs
on: [push]

jobs:
  build:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Docs
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: dokkaJavadoc
        id: generate-docs
      - name: Switch Branch & Commit
        run: |
          git fetch
          git checkout gh-pages
          git add .
          git commit -m "${branch#refs/heads/}#$(git rev-parse --short "$GITHUB_SHA") docs"
        id: commit
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
        id: push
